// Auto-generated by tools/assemble.py
module program_rom(
    input  wire [7:0]  addr,
    output reg  [15:0] data
);
    always @(*) begin
        case (addr)
            8'h00: data = 16'h1055; // LDI R0, 0x55
            8'h01: data = 16'hE001; // OUT 0x01, R0
            8'h02: data = 16'h1241; // LDI R1, 0x41
            8'h03: data = 16'hE211; // OUT 0x11, R1
            8'h04: data = 16'h14A5; // LDI R2, 0xA5
            8'h05: data = 16'hE421; // OUT 0x21, R2
            8'h06: data = 16'h1601; // LDI R3, 0x01
            8'h07: data = 16'hE620; // OUT 0x20, R3
            8'h08: data = 16'hD820; // IN  R4, 0x20
            8'h09: data = 16'h1A01; // LDI R5, 0x01
            8'h0A: data = 16'h5940; // AND R4, R5
            8'h0B: data = 16'hC008; // JNZ wait_spi
            8'h0C: data = 16'hDC21; // IN  R6, 0x21
            8'h0D: data = 16'hEC01; // OUT 0x01, R6
            8'h0E: data = 16'hF000; // HLT
            default: data = 16'h0000;
        endcase
    end
endmodule
